import type { Metadata } from "next";
import Providers from "@/providers";
import { Roboto } from "next/font/google";

import "@/styles/globals.css";

const roboto = Roboto({
  variable: "--font-primary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
